### ISSUE TITLE
Adicionar esquema relacional na wiki

### ISSUE THREAD

**Issue by tomtomesteves** [easyfastfood/easyFood#18]
Criar e salvar em uma pagina na wiki o esquema relacional do banco no estado atual.

**Comment by tomtomesteves** [comment]
Adicionei uma pagina na wiki explicando a estrutura do banco de dados: [link](https://github.com/easyfastfood/easyFood/wiki/Banco-de-dados)
@marco-silveira @GustavoBBP @RafaelMassoni 
Deem um ok porfavor, qualquer alteração que vocês achem necessária podem pedir por comentário aqui mesmo.

**Comment by RafaelMassoni** [comment]
Na tabela Restaurantes: a coluna categoria deveria ser id_categoria e a coluna descrição acredito que seria melhor se fosse descricao sem o ç e acento

**Comment by tomtomesteves** [comment]
♻️ @RafaelMassoni

**Comment by RafaelMassoni** [comment]
lgtm!

**Comment by marco-silveira** [comment]
LGTM
