### ISSUE TITLE
Adicionar fluxo do gqlgen na wiki

### ISSUE THREAD

**Issue by marco-silveira** [easyfastfood/easyFood#30]
Podemos incluir na wiki o fluxo de atualização do schema da API GraphQL:

- Explicar sucintamente o que é o glqgen e graphql;
- Explicar como funciona o schema.graphql
- Explicar como funciona o gqlgen.yml
- Descrever o fluxo de adicionar uma entidade no schema e a geração dos códigos (make gqlgen)

**Comment by RafaelMassoni** [comment]
Terminei a primeira versão da wiki explicando conceitos gerais do GraphQL e gqlgen. Por favor me informar a respeito de qualquer alteração ou se está aprovada.

[Link de acesso](https://github.com/easyfastfood/easyFood/wiki/GraphQL-e-gqlgen)

**Comment by marco-silveira** [comment]
@RafaelMassoni Os paths onde os arquivos do gqlgen serão gerados mudou: https://github.com/easyfastfood/easyFood/pull/34/files

**Comment by RafaelMassoni** [comment]
♻️ @marco-silveira

**Comment by marco-silveira** [comment]
LGTM

**Comment by tomtomesteves** [comment]
LGTM ✔️
