### ISSUE TITLE
Pesquisar como estruturar o frontend

### ISSUE THREAD

**Issue by marco-silveira** [easyfastfood/easyFood#8]
Precisamos definir o funcionamento básico, quais tecnologias usar, etc. Algumas ideias iniciais são React e MaterialUI para os templates HTML/CSS.

**Comment by tomtomesteves** [comment]
Depois de analisar as tecnologias usadas no mercado, decidi usar o REACT para criar o frontend da aplicação pelos seguintes motivos:
* Templates mais fáceis de encontrar
* Muito usado na comunidade
* Integração com a maioria das api's

**Comment by tomtomesteves** [comment]
@marco-silveira @RafaelMassoni 
Se puderem dar um ok já finalizo esta issue.

**Comment by RafaelMassoni** [comment]
lgtm

**Comment by marco-silveira** [comment]
lgtm
